### ISSUE TITLE
Errors in generated.cu running easy tests

### ISSUE THREAD

**Issue by zenlc2000** [pcpratts/rootbeer1#176]
I was having a problem with errors in generated.cu when I was building my own project so I decided to try running tests to see what I would get. My MacBook Pro has an NVidia 650m with 1GB onboard memory and 8GB RAM, with JDK 1.7. Using this command line:

**java -jar -Xmx6g Rootbeer-1.2.4.jar -64bit -runeasytests**

several of the tests comeback with errors like: 

/Users/zen/.rootbeer/generated.cu(433): warning: statement is unreachable

/Users/zen/.rootbeer/generated.cu(462): warning: statement is unreachable

/Users/zen/.rootbeer/generated.cu(476): warning: statement is unreachable

/Users/zen/.rootbeer/generated.cu(515): error: identifier "invoke_java_util_List_add1_20_" is undefined

1 error detected in the compilation of "/var/folders/24/6dnlf4sj52n7prtkcd5ltwtr0000gn/T//tmpxft_00002f14_00000000-12_generated.compute_20.cpp1.ii".
generating serialization bytecode...
added interface CompiledKernel
running transform2 on: <org.trifort.rootbeer.testcases.rootbeertest.serialization.LongArraysRunOnGpu: void gpuMethod()>...
compiling CUDA code for 64bit only...
generating serialization bytecode...
added interface CompiledKernel

Part of my interest comes from the fact that when I'm building my project, when I include a small storage class I wrote in my kernel code, I get similar errors.

On a related note, I tried making that storage class as an inner class and it kept telling me it couldn't find one of the methods and to check dependancies then generated similar errors/warnings as above.

Any ideas?

Thanks

**Comment by zenlc2000** [comment]
I also just noticed this on the bottom of easy tests:

[TEST 1/104] org.trifort.rootbeer.testcases.rootbeertest.gpurequired.NewOnGpu@2d6691a
org.trifort.rootbeer.runtime.CudaErrorException: CUDA_ERROR_OUT_OF_MEMORY: Error in cuMemAlloc: gpu_object_mem
	at org.trifort.rootbeer.runtime.CUDAContext.nativeBuildState(Native Method)
	at org.trifort.rootbeer.runtime.CUDAContext.access$1100(CUDAContext.java:17)
	at org.trifort.rootbeer.runtime.CUDAContext$GpuEventHandler.onEvent(CUDAContext.java:315)
	at org.trifort.rootbeer.runtime.CUDAContext$GpuEventHandler.onEvent(CUDAContext.java:308)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x0000000103dd81f8, pid=941, tid=9987

 JRE version: Java(TM) SE Runtime Environment (7.0_71-b14) (build 1.7.0_71-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.71-b01 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.dylib+0x1c51f8]  void PSParallelCompact::mark_and_push<unsigned int>(ParCompactionManager*, unsigned int*)+0x58

**Comment by pcpratts** [comment]
Right now ArrayList does not work on my test cases. It will take more work in class loading and code generation to make this happen. When I am using Rootbeer right now I convert everything to arrays of primitive types and custom composite classes if needed. I do not use any components in the JDK including ArrayList. 

Currently I am trying to accelerate JAHMM (Java Hidden Markov Models) library using Rootbeer/GPU. Doing this works pretty well for my test cases.

On your application, OutOfMemory errors can be fixed by buying a GPU with 3-6GB of ram (approx $2000-3000). You will want to buy a device and program to it, since changing thread/block count can drastically change performance. Please email pcpratts@trifort.org if you want to setup a chat where I will ask about your algorithm and data structures and give advice on getting the most from a GPU

**Comment by zenlc2000** [comment]
Are you recommending more GPU memory for building, also? Unfortunately my MacBook can't upgrade the video card but I guess I can move my development over to AWS.

How about those same generated.cu errors with included class/inner class? This is the class I'm trying to use:

package Brush;

public class KVPair
{
	private String _key;
	private String[] _value;
	
	private int _size = 0;
	
	public KVPair()
	{
		
	}
	
	public KVPair( int size )
	{
		_value = new String[size + 1];
		
	}
	
	public synchronized void addValue(String val)
	{
		_value[_size] = val;
		_size++;
	}
	public synchronized void setKey(String k)
	{
		_key = k;
	}
	public String getKey()
	{
		return _key;
	}
	
	public String[] getValues()
	{
		return _value;
	}
}

As stated, I'm making an array of KVPairs in the Kernel class, like so:

KVPair[] fields = new KVPair[5];

Any thoughts?

Thanks

**Comment by pcpratts** [comment]
Can you make a private github repository and give me access so I can debug the entire application? Or send me a zip?

**Comment by zenlc2000** [comment]
Sent link to github. Check the GenNonContainedReads.reducer and GenNonContainedReadsKernel classes along with KVPair. 

Probably not the best way to use a GPU, but that's why they call it research :).

**Comment by jamestalmage** [comment]
@pcpratts 
Is running the complete test suite on the mentioned hardware a lost cause? (`NVidia 650m with 1GB`).

**Comment by pcpratts** [comment]
@jamestalmage 
Yes probably. Email pcpratts@trifort.org if you want me to send a dissertation draft and go over slides on GPU programming and Rootbeer. Most core things work if you know the tricks on how to use Rootbeer.  I am available for chat question/answer too.
