### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by andronix3** [pcpratts/rootbeer1#187]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\andro\.rootbeer\rootbeer_cuda_x64.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.trifort.rootbeer.runtime.CUDALoader.doLoad(CUDALoader.java:93)
        at org.trifort.rootbeer.runtime.CUDALoader.load(CUDALoader.java:86)
        at org.trifort.rootbeer.runtime.Rootbeer.<clinit>(Rootbeer.java:15)
        at org.trifort.rootbeer.entry.Main.printDeviceInfo(Main.java:222)
        at org.trifort.rootbeer.entry.Main.run(Main.java:187)
        at org.trifort.rootbeer.entry.Main.main(Main.java:244)

I checked rootbeer_cuda_x64.dll is present and is about 60KB

C:\Users\andro\.rootbeer>dir

15.08.2016  00:32    <DIR>          .
15.08.2016  00:32    <DIR>          ..
15.08.2016  00:50            61.440 rootbeer_cuda_x64.dll
15.08.2016  00:50            59.392 rootbeer_x64.dll
               2 Datei(en),        120.832 Bytes
               2 Verzeichnis(se), 550.620.565.504 Bytes frei

**Comment by mxmlnkn** [comment]
Is the paste correct? I get the feeling, that
`C:\Users\andro.rootbeer\rootbeer_cuda_x64.dll`
should be
`C:\Users\andro\.rootbeer\rootbeer_cuda_x64.dll`
note the additional backslash.

**Comment by andronix3** [comment]
Yes, backslash was lost somewhere...

**Comment by mxmlnkn** [comment]
What are the exact steps to reproduce? E.g. does this happen when compiling with Rootbeer or when running a compiled Rootbeer program?

Do you have CUDA installed? (It is necessary)

**Comment by andronix3** [comment]
It was just fist try with rootbeer
java -jar rootbeer.jar -printdeviceinfo

okay I forgot to install CUDA

**Comment by andronix3** [comment]
installed CUDA, still same problem.

**Comment by andronix3** [comment]
What I don't understand, there are must be some kind distribution package for CUDA. I can't tell people "To use my program, please download and install 1 GB CUDA package from NVidia"

**Comment by mxmlnkn** [comment]
I'm not sure if a CUDA-installation is needed for execution, just for compilation.
But it looked liked rootbeer_cuda_x64.dll is  missing some dependency and the only dependency which that should need and I know of should be `cuda.h` (and `jni.h`).
I only tested Rootbeer with Linux until now, so I can only guess as to what is wrong.
