### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: ScalarAddKernel cannot be cast to org.trifort.rootbeer.runtime.CompiledKernel

### ISSUE THREAD

**Issue by jasonwee** [pcpratts/rootbeer1#189]
hi there, 

going over this example https://github.com/pcpratts/rootbeer1/tree/master/examples/ScalarAddApp/src/org/trifort/rootbeer/examples/scalaradd

and then compile rootbeer using the source from this repository, and then run the code using the following command

    $ optirun /jvm/jdk1.8.0_102/bin/java -cp ../../../lib/Rootbeer.jar:. ScalarAddApp
    startarray[0]: 0
    startarray[1]: 1
    startarray[2]: 2
    startarray[3]: 3
    startarray[4]: 4
    startarray[5]: 5
    startarray[6]: 6
    startarray[7]: 7
    startarray[8]: 8
    startarray[9]: 9
    Exception in thread "main" java.lang.ClassCastException: ScalarAddKernel cannot be cast to org.trifort.rootbeer.runtime.CompiledKernel
    	at org.trifort.rootbeer.runtime.CUDAContext.setKernel(CUDAContext.java:119)
    	at org.trifort.rootbeer.runtime.Rootbeer.run(Rootbeer.java:84)
    	at ScalarAddApp.multArray(ScalarAddApp.java:19)
    	at ScalarAddApp.main(ScalarAddApp.java:38)

what did i do wrong?

**Comment by mxmlnkn** [comment]
I'm really unsure about the usage of optirun. Did you try it without that?
As far as I can tell it only redirects OpenGL commands:

> Normally you do not use optirun for your window manager, installations, or other **non-graphic**, resource intensive programs. The optirun command is mainly used for graphic demanding programs (ex. games).
> https://wiki.ubuntu.com/Bumblebee

If you want to user another GPU, you have to do that inside Rootbeer.
I'm not sure, though, if the usage of optirun should lead to such errors.

I also had this ClassCastException very often, but that was because I tried running multiple instances of a rootbeer program while rootbeer is not thread-safe. Something like:

    java MyRootbeerProgram.jar -useGPU0 & java MyRootbeerProgram.jar -useGPU1 &

I tried to make Rootbeer thread-safe in my own fork, if you are really desperate you could try that, but I also changed some other things which could lead to surprises and difficulties.

**Comment by jasonwee** [comment]
optirun is a command to enable the discreet gpu (nvidia gpu). Without this command (using the default intel), get npe or exception, something like that, can't remember. 

thank, i will try that, no urgent, still learning all this. if you need help on testing, send me a message, would like to help.

**Comment by jasonwee** [comment]
rerun with and without optirun

```
$ /jvm/jdk1.8.0_102/bin/java -cp ../../../lib/Rootbeer.jar:. ScalarAddApp 
startarray[0]: 0
startarray[1]: 1
startarray[2]: 2
startarray[3]: 3
startarray[4]: 4
startarray[5]: 5
startarray[6]: 6
startarray[7]: 7
startarray[8]: 8
startarray[9]: 9
Exception in thread "main" java.lang.NullPointerException
	at org.trifort.rootbeer.runtime.Rootbeer.run(Rootbeer.java:81)
	at ScalarAddApp.multArray(ScalarAddApp.java:23)
	at ScalarAddApp.main(ScalarAddApp.java:42)



$ optirun /jvm/jdk1.8.0_102/bin/java -cp ../../../lib/Rootbeer.jar:. ScalarAddApp 
startarray[0]: 0
startarray[1]: 1
startarray[2]: 2
startarray[3]: 3
startarray[4]: 4
startarray[5]: 5
startarray[6]: 6
startarray[7]: 7
startarray[8]: 8
startarray[9]: 9
Exception in thread "main" java.lang.ClassCastException: play.learn.gpu.rootbeer1.ScalarAddKernel cannot be cast to org.trifort.rootbeer.runtime.CompiledKernel
	at org.trifort.rootbeer.runtime.CUDAContext.setKernel(CUDAContext.java:119)
	at org.trifort.rootbeer.runtime.Rootbeer.run(Rootbeer.java:84)
	at ScalarAddApp.multArray(ScalarAddApp.java:23)
	at ScalarAddApp.main(ScalarAddApp.java:42)
```

**Comment by mxmlnkn** [comment]
Just for completeness: how are you compiling ScalarAddApp?

**Comment by jasonwee** [comment]
using eclipse compiler

**Comment by mxmlnkn** [comment]
Actually for me it works. It's a bit problematic to find a bug if I myself can't reproduce it. Here are my steps:

    cd examples/ScalarAddApp
    ant jar
    cd dist
    java -jar ../../../Rootbeer.jar ScalarAddApp{,-GPU}.jar
        In file included from /usr/local/cuda/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
        /usr/local/cuda/include/host_config.h:105:2: error: #error -- unsupported GNU version! gcc 4.10 and up are not supported!
         #error -- unsupported GNU version! gcc 4.10 and up are not supported!
          ^~~~~
        In file included from /usr/local/cuda/include/cuda_runtime.h:62:0,
                         from <command-line>:0:
        /usr/local/cuda/include/host_config.h:105:2: error: #error -- unsupported GNU version! gcc 4.10 and up are not supported!
         #error -- unsupported GNU version! gcc 4.10 and up are not supported!
          ^~~~~
        generating serialization bytecode...
     -> problem: gcc 5 not supported by CUDA 7

    sudo update-alternatives --config gcc
     -> select gcc 4.9
    java -jar ../../../Rootbeer.jar ScalarAddApp{,-GPU}.jar
    # Finally run the GPU version
    java -jar ScalarAddApp-GPU.jar
