### ISSUE TITLE
RootbeerClassLoader get NullPointerException

### ISSUE THREAD

**Issue by mohsen-mahmoudi** [pcpratts/rootbeer1#193]
hi all, when i run the ScalarAddApp Sample , i give this exception! compile java version is 1.8. what thing is wrong?

```
Mohsen@DESKTOP-HVHPPOF MINGW64 /d/Workspace/rtree-workspace/rootbeer1/examples/ScalarAddApp (master)
$ ./compile-gpu
Buildfile: D:\Workspace\rtree-workspace\rootbeer1\build.xml

clean:
   [delete] Deleting directory D:\Workspace\rtree-workspace\rootbeer1\build

BUILD SUCCESSFUL
Total time: 0 seconds
Buildfile: D:\Workspace\rtree-workspace\rootbeer1\build.xml

compile:
    [mkdir] Created dir: D:\Workspace\rtree-workspace\rootbeer1\build\classes
    [javac] Compiling 462 source files to D:\Workspace\rtree-workspace\rootbeer1\build\classes
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\generate\opencl
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\runtime\nemu
     [copy] Copying 1 file to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\runtime\nemu
     [copy] Copying 10 files to D:\Workspace\rtree-workspace\rootbeer1\build\classes\org\trifort\rootbeer\runtime\binaries

jar:
      [jar] Building jar: D:\Workspace\rtree-workspace\rootbeer1\dist\Rootbeer1.jar

BUILD SUCCESSFUL
Total time: 6 seconds
Packing up to: Rootbeer.jar
Buildfile: D:\Workspace\rtree-workspace\rootbeer1\examples\ScalarAddApp\build.xml

compile:

jar:
      [jar] Building jar: D:\Workspace\rtree-workspace\rootbeer1\examples\ScalarAddApp\dist\ScalarAddApp.jar
      [jar] Building jar: D:\Workspace\rtree-workspace\rootbeer1\examples\ScalarAddApp\dist\ScalarAddApp-GPU.jar

BUILD SUCCESSFUL
Total time: 0 seconds
caching package names for: D:\Workspace\rtree-workspace\rootbeer1\examples\ScalarAddApp\dist\ScalarAddApp.jar
caching package names for: D:\Workspace\rtree-workspace\rootbeer1\Rootbeer.jar
caching package names for: C:\Java\jdk1.8.0_45\jre\lib\rt.jar
cpool == null
java.lang.NullPointerException
        at soot.rbclassload.RootbeerClassLoader.loadHierarchySootClasses(RootbeerClassLoader.java:963)
        at soot.rbclassload.RootbeerClassLoader.loadNecessaryClasses(RootbeerClassLoader.java:294)
        at org.trifort.rootbeer.entry.RootbeerCompiler.setupSoot(RootbeerCompiler.java:198)
        at org.trifort.rootbeer.entry.RootbeerCompiler.compile(RootbeerCompiler.java:219)
        at org.trifort.rootbeer.entry.RootbeerCompiler.compile(RootbeerCompiler.java:213)
        at org.trifort.rootbeer.entry.Main.run(Main.java:208)
        at org.trifort.rootbeer.entry.Main.main(Main.java:244)
caching package names for: dist\ScalarAddApp.jar
remapping class: java.util.concurrent.atomic.AtomicLong
java.lang.NullPointerException
        at soot.rbclassload.RootbeerClassLoader.remapClasses(RootbeerClassLoader.java:998)
        at soot.rbclassload.RootbeerClassLoader.loadNecessaryClasses(RootbeerClassLoader.java:295)
        at org.trifort.rootbeer.entry.RootbeerCompiler.setupSoot(RootbeerCompiler.java:198)
        at org.trifort.rootbeer.entry.RootbeerCompiler.compile(RootbeerCompiler.java:219)
        at org.trifort.rootbeer.entry.RootbeerCompiler.compile(RootbeerCompiler.java:213)
        at org.trifort.rootbeer.entry.Main.run(Main.java:208)
        at org.trifort.rootbeer.entry.Main.main(Main.java:244)

```

**Comment by mxmlnkn** [comment]
See #175
